#!/bin/bash
if [ -z "$1" ]; then 
  echo usage: $0 testNumber jvmName
  exit
 fi
java -cp 'jars/*' -Djava.security.manager -Djava.security.policy=dcvm.policy fr.upmc.components.testdistributed.DCVM$1 $2 config.xml